apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-deployment
  labels:
    app: helloworld
spec:
  selector:
    matchLabels:
      app: helloworld
  replicas: 1
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: helloworld
        image: 1148541663/test-demo-public:d37122c67dd921246aa07dbbe7726045ff25a897
        resources:
          requests:
           cpu: 100m
           memory: 100Mi
        ports:
        - containerPort: 9000
