apiVersion: v1
kind: Service
metadata:
  name: helloworld-service
  labels:
    app: helloworld
spec:
  type: NodePort
  ports:
  - port: 9000
    targetPort: 9000
    nodePort: 30011
    name: http
  selector:
    app: helloworld
    
  #externalIPs:
  #  - 80.11.12.10

