apiVersion: apps/v1
kind: Deployment
metadata:
  name: my_web
spec:
 selector:
    matchLabels:
      app: hello_world
      tier: my_web
  replicas: 3
  template:
    metadata:
      labels:
        app: hello_world
        tier: my_web
    spec:
      containers:
      - name: my_web_container
        image: 1148541663/test-demo-public
        ports:
        - containerPort: 9000
