apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    app: web-app
#    role: slave
    tier: backend
spec:
  ports:
  - port: 9000
  selector:
    app: web-app
 #   role: slave
    tier: backend
