apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  selector:
    matchLabels:
      app: web-app
      #role: slave
      tier: backend
  replicas: 2
  template:
    metadata:
      labels:
        app: web-app
        #role: slave
        tier: backend
    spec:
      containers:
      - name: container
        image: 1148541663/test-demo-public
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 9000
